server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
#    config:
#      enabled: true
#      uri: http://localhost:9296
    gateway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:9002
          predicates:
            - Path=/user/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBackMethod
        - id: ORDER-SERVICE
          uri: http://localhost:9001
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBackMethod
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost