server:
  port: 9090

spring:
  application:
    name: Admin-server
  zipkin:
    base-url: http://127.0.0.1:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"

  security:
    enabled: false