spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      database: datainfo
      port: 27017
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port: 9002

#added blow statements in the git repository on name of application.yml
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

  security:
    enabled: false